chitfund/urls.py
from django.contrib import admin
from django.urls import path, include
from .view import LandingPageView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (LoginView,
                                       LogoutView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from client.views import ClientsignupView
# Namespace to identify the app we are using if we have multiple apps
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    # Apps usrls
    path('client/', include('client.urls', namespace="client" )),
    path('kuries/', include('kuries.urls')),
    path('financial/', include('financial_analyzer.urls')),
    path('namgen/', include('trial1.urls',namespace='namegen')),
    path('chatbot/', include('chatbot.urls',namespace='chatbot')),
    path('ocr/', include('ocr_app.urls', namespace='ocr_app')),
    path('transcribe/', include('transcribe_app.urls', namespace='transcribe_app')),
    path('food/', include('food_app.urls', namespace='food_app')),
    path('enlaw/', include('enlaw.urls')),
    # login
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', ClientsignupView.as_view(), name='signup'),
    path('passwordReset/', PasswordResetView.as_view(), name='password-reset'),
    path('passwordResetDone/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('passwordResetConfirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('passwordResetComplete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

# checkign for debug mode
if settings.DEBUG:
    # this is for user uploads for media files
    #urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

client/urls.py
from django.urls import path
from . import views

# To identify this App  when we have multiple app
app_name = "client"

urlpatterns = [
    path('', views.ClientListView.as_view(), name='client-list'),

    path('create/', views.ClientCreateView.as_view(), name='client-create'),

    path('<int:pk>/', views.ClientDetailView.as_view(), name='client-info'),

    path('<int:pk>/update/', views.ClientUpdateView.as_view(), name='client-update'),

    path('<int:pk>/delete/', views.ClientDeleteView.as_view(), name='client-delete'),

    path('assign/<int:pk>/', views.clientAssignView.as_view(), name='client-assign'),

    path('category/', views.categoryListView.as_view(), name='client-category'),

    path('categoryDetail/<int:pk>/', views.categoryDetailView.as_view(), name='client-category-detail'),

    path('categoryDetailUpdate/<int:pk>/', views.clientCategoryupdateView.as_view(), name='client-category-update'),

    path('restrict/', views.ClientRestrict, name='client-restrict'),

    path('settings/', views.ClientSettingsView.as_view(), name='client-settings'),
]

enlaw/urls.py
from django.urls import path
from . import views
from .views import list_static_templates

app_name = 'enlaw'

urlpatterns = [
    path('', list_static_templates, name='template_list'),
    path('template/<int:pk>/', views.TemplateDetailView.as_view(), name='template_preview'),
    path('edit/<int:template_id>/', views.edit_document, name='edit_document'),
    path('edit-static/<str:template_path>/', views.edit_static_template, name='edit_static_template'),
    path('simple-form/<str:template_path>/', views.simple_form_edit, name='simple_form_edit'),
    path('save/<int:document_id>/', views.save_document_progress, name='save_progress'),
    path('export/<int:document_id>/', views.export_document, name='export_document'),
    
    # Dynamic form editing with HTMX
    path('dynamic-form/<int:template_id>/', views.dynamic_form_edit, name='dynamic_form_edit'),
    path('update-field/<int:template_id>/<str:field_name>/', views.update_field, name='update_field'),
]

kuries/urls.py
from django.urls import path
from .views import chitfundlistview, chitfundCreateview, chitfundDetaiView, chitfundUpdateView, chitfundDeleteView


# To identify this App  when we have multiple app
app_name = "kuries"

urlpatterns = [
    path('', chitfundlistview.as_view(), name='chitfund-list'),
    path('create/', chitfundCreateview.as_view(), name='chitfund-create'),
    path('<int:pk>', chitfundDetaiView.as_view(), name='chitfund-info'),

    path('update/<int:pk>', chitfundUpdateView.as_view(), name='chitfund-update'),

    path('delete/<int:pk>', chitfundDeleteView.as_view(), name='chitfund-delete')
]

client/models.py
# importing the db database
# lot of features we are inheriting from models
# pre build features
from django.db import models
#We are using this to reference user to the chitFund# means chitfund are the users of the apps
from django.contrib.auth.models import AbstractUser#get_user_model
#User = get_user_model()
# post save is executed whenn the a save function is executed
from django.db.models.signals import post_save
from django.utils import timezone
from django.contrib.auth import get_user_model

import uuid
import json

"""
    .objects is caloling the model manager
    on the manager we get access to methods of the database
    we can user create , get, save methods. cerate cerates a new instance
    query set using manager, all() , filter(on something)
    filter(field__gt = xxx) greater than this number
    Quert set says it all the instances and  you can run a query
    An instance is nothing but the instace of the filtered object
    ORM concept is used to work on database without working on sequel query interaction by python
"""



# Creating my custom user model
class User(AbstractUser):
    is_chitfund_owner = models.BooleanField(default=False)
    is_chitfund_user = models.BooleanField(default=False)
    is_namegen_user = models.BooleanField(default=False)
    is_food_app_user = models.BooleanField(default=False)
    is_ocr_app_user = models.BooleanField(default=False)
    is_transcribe_app_user = models.BooleanField(default=False)
    is_chatbot_user = models.BooleanField(default=False)
    is_kuries_user = models.BooleanField(default=False)
    is_financial_analyzer_user = models.BooleanField(default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.user.username



# chitfund model
class ChitFund(models.Model):
    # below commented field is already there
    # in the User part hence commented
    name = models.CharField(max_length = 200)
    about = models.TextField(null=True)
    address = models.TextField(max_length=400,blank=True,null=True)
    state = models.CharField(max_length=150)
    country = models.CharField(max_length=150)
    pin = models.IntegerField(blank=True, null=True)
    # we need to have one to one relation between
    # user and the agent which is the user itself

    #### Have to think on below line ############################################
    #user = models.OneToOneField(User, on_delete=models.CASCADE)
    #############################################################################

    # auto_now it will automatically store the updated value int his field
    #updated = models.DateTimeField(auto_now=True)
    # auto_now_add takes a snapshot of when it was first added the instance
    #created = models.DateTimeField(auto_now_add=True)

    owner = models.ForeignKey(UserProfile,
                              on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name

# Create your models here. Table schema
class Client(models.Model):

    # Gender categories
    MALE = 1
    FEMALE = 2
    GENDER = (
        (MALE,"Male"),
        (FEMALE, "Female"),
    )

    # Marriage categories
    MARRIED = 1
    SINGLE = 2
    OTHERS = 3
    MARRIAGE = (
        (MARRIED,"Married"),
        (SINGLE, "Single"),
        (OTHERS,"Others")
    )

    # Education categories
    POSTGRADUATE=1
    GRADUATE=2
    HIGHSCHOOL=3
    SCHOOL=4
    OTHERS=5
    UNKNOWN=6

    EDU =(
        (POSTGRADUATE,"Postgraduate"),
        (GRADUATE,"Graduate"),
        (HIGHSCHOOL,"Highschool"),
        (SCHOOL,"School"),
        (OTHERS,"Others"),
        (UNKNOWN,"Unknown")
    )

    # Soucre choice
    SOURCE_CHOICES = (
        ('YT','Youtube'),
        ('Google','Google'),
        ('Linkedin','Linkedin')

    )

    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    age = models.IntegerField(default=18)

    sex = models.IntegerField(
        choices=GENDER,
        default=MALE,
    )

    education= models.IntegerField(
        choices=EDU,
        default=UNKNOWN,
    )

    marriage = models.IntegerField(
        choices=MARRIAGE,
        default=SINGLE,
    )

    phoned = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=13)
    email = models.EmailField()
    company = models.CharField(max_length=150,blank=True,null=True)
    description = models.TextField()
    source = models.CharField(choices=SOURCE_CHOICES, max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)
    # Blank means you ar esubmitting emply string, null means not having value in the database
    #profile_picture = models.ImageField(blank=True, null=True,
    #default="eneru_logo.jpg")
    #special_file = models.FileField(blank=True,null=True)

    # Relationship field connection betn tables
    # how to handle when the related instance is delete to handle
    # models.CASCADE will delete the client when chitfund is deleted
    chitfundName = models.ForeignKey("ChitFund",
                                     related_name="users", 
                                     on_delete=models.SET_NULL,
                                     blank=True,
                                     null=True)

    owner = models.ForeignKey(UserProfile,
                              on_delete=models.SET_NULL, blank=True, null=True)


    category = models.ForeignKey("Category",
                                 related_name="clients",
                                 on_delete=models.SET_NULL,
                                 blank=True,
                                 null=True)
    # auto_now it will automatically store the updated value int his field
    #updated = models.DateTimeField(auto_now=True)
    # auto_now_add takes a snapshot of when it was first added the instance
    #created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.first_name



class Category(models.Model):
    name = models.CharField(max_length=30) # New, Processing, Opened, Ongoing, Defaulted, Completed
    owner = models.ForeignKey(UserProfile,
                              on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name


class Template(models.Model):
    CATEGORY_CHOICES = [
        ('LEGAL', 'Legal'),
        ('BUSINESS', 'Business'),
        ('ACADEMIC', 'Academic'),
    ]
    
    title = models.CharField(max_length=255)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    content = models.TextField(help_text="Use {{placeholder}} syntax for dynamic fields")
    created_at = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return f"{self.title} ({self.get_category_display()})"
    
    class Meta:
        ordering = ['-created_at']

class FilledTemplate(models.Model):
    template = models.ForeignKey(Template, on_delete=models.PROTECT, related_name='filled_templates')
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    input_data = models.JSONField(default=dict, help_text="Stores user inputs for placeholders")
    audio_recordings = models.JSONField(default=dict, help_text="Stores paths to audio recordings")
    export_format = models.CharField(max_length=10, choices=[('PDF', 'PDF'), ('DOCX', 'DOCX')])
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    
    def __str__(self):
        return f"{self.template.title} - {self.created_at.strftime('%Y-%m-%d %H:%M')}"
    
    class Meta:
        ordering = ['-modified_at']
        indexes = [
            models.Index(fields=['uuid']),
            models.Index(fields=['user', '-modified_at']),
        ]


# very powerful signals when some events needs to happen after an event
def post_user_created_signal(sender, instance, created, **kwargs):
    #print(instance, created)
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_created_signal, sender=User)

client/forms.py
from django import forms
from django.forms import ModelForm
from .models import Client, User, ChitFund
from django.contrib.auth.forms import UserCreationForm


# class ClientForm(forms.Form):
#     first_name = forms.CharField()
#     last_name = forms.CharField()
#     age = forms.IntegerField(min_value=18)


class ClientForm(ModelForm):
    class Meta:
        model = Client

        fields = '__all__'

class ChitfundUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2',
            'is_chitfund_owner',
            'is_chitfund_user',
            'is_namegen_user',
            'is_food_app_user',
            'is_ocr_app_user',
            'is_transcribe_app_user',
            'is_chatbot_user',
            'is_kuries_user'
        )

class clientAssignForm(forms.Form):
    # Django provides us with Model choice instaead which takes in the
    # queryset from the models
    chitfund = forms.ModelChoiceField(queryset=ChitFund.objects.none())

    # Creating a dynamic updating queryset for the form above
    def __init__(self, *args, **kwargs):
        # getting the request from views here
        request = kwargs.pop("request")
        chitfunds = ChitFund.objects.filter(owner=request.user.userprofile)
        super(clientAssignForm, self).__init__(*args, **kwargs)
        self.fields["chitfund"].queryset = chitfunds

class clientCategoryUpdateForm(ModelForm):

    class Meta:
        model = Client
        fields = ['category']


class LoginUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','password']

client/templates/client/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Eneru Client Management{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    {% block extra_css %}{% endblock %}
</head>
<body class="bg-gray-100 min-h-screen">
    <nav class="bg-white shadow-lg">
        <div class="max-w-7xl mx-auto px-4">
            <div class="flex justify-between h-16">
                <div class="flex">
                    <div class="flex-shrink-0 flex items-center">
                        <span class="text-2xl font-bold text-indigo-600">Eneru Kuries</span>
                    </div>
                    <div class="ml-10 flex items-center space-x-4">
                        <a href="{% url 'landing-page' %}" class="text-gray-700 hover:text-indigo-600 transition-colors duration-300">
                            <i class="fas fa-home"></i> Home
                        </a>
                    </div>
                </div>
                {% if request.user.is_chitfund_owner %}
                <div class="flex items-center space-x-4">
                    <a href="{% url 'kuries:chitfund-list' %}" class="text-gray-700 hover:text-indigo-600 transition-colors duration-300">
                        <i class="fas fa-list"></i> Chitfunds
                    </a>
                    <a href="{% url 'client:client-category' %}" class="text-gray-700 hover:text-indigo-600 transition-colors duration-300">
                        <i class="fas fa-tags"></i> Categories
                    </a>
                </div>
                {% endif %}
            </div>
        </div>
    </nav>

    <main class="container mx-auto px-4 py-8">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="bg-white shadow-lg mt-8">
        <div class="max-w-7xl mx-auto py-4 px-4">
            <p class="text-center text-gray-600">2024 Eneru (opc). All rights reserved.</p>
        </div>
    </footer>

    <!-- JavaScript -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

client/templates/client/client_assign.html
{% extends "base.html" %}

{% block title %}
    ClientAssign
{% endblock title %}

{% block content %}
    <a href="{% url 'client:client-list' %}">Home</a>
    <hr/>
    <h1> Assign an Chitfund to this client </h1>
    <form method="POST">
        {% csrf_token %} <!--Security aspect of Django -->
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

client/templates/client/client_category_update.html
{% extends "client/base.html" %}
{% load tailwind_filters %}

{% block title %}
clientUpdate
{% endblock title %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">Client</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">This are the details for {{ client.first_name }} {{ client.last_name }}</h1>
                <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
                src="https://dummyimage.com/400x400">
                <div class="flex mb-4">
                    <a href="{% url 'client:client-info' client.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
                    <a href="{% url 'client:client-category-update' client.pk %}"
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Category</a>
                    <a href="{% url 'client:client-update' client.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update
                        Details</a>
                </div>
                <form method="POST" action="#">
                    {% csrf_token %} <!--Security aspect of Django -->
                    {{ form|crispy }}
                    <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md" >Submit</button>
                </form>
            </div>

        </div>
    </div>
</section>

{% endblock content %}

client/templates/client/client_info.html
{% extends "base.html" %}

{% block title %}
clientInfo
{% endblock title %}

{% block content %}

<div class="min-h-screen bg-gradient-to-br from-indigo-100 via-white to-purple-100">
    <section class="text-gray-600 body-font overflow-hidden">
        <div class="container px-5 py-24 mx-auto">
            <div class="lg:w-4/5 mx-auto flex flex-wrap">
                <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                    <h2 class="text-sm title-font text-gray-500 tracking-widest">Client</h2>
                    <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">This are the details for {{ client.first_name }} {{ client.last_name }}</h1>
                    <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
                    <div class="flex mb-4">
                        <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
                        <a href="{% url 'client:client-category-update' client.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
                        <a href="{% url 'client:client-update' client.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update Details</a>
                    </div>
                    <p class="leading-relaxed mb-4">{{ client.description }}</p>
                    <div class="flex border-t border-gray-200 py-2">
                        <span class="text-gray-500">Age</span>
                        <span class="ml-auto text-gray-900">{{ client.age }} </span>
                    </div>
                    <div class="flex border-t border-gray-200 py-2">
                        <span class="text-gray-500">Source</span>
                        <span class="ml-auto text-gray-900">{{ client.source }}</span>
                    </div>
                    <div class="flex border-t border-gray-200 py-2">
                        <span class="text-gray-500">Status</span>
                        <span class="ml-auto text-gray-900">{{ client.category }}</span>
                    </div>
                    <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                        <span class="text-gray-500">Fund where the client opened their account</span>
                        <span class="ml-auto text-gray-900">{{client.chitfundName}}</span>
                    </div>
                    <div class="flex">
                        <a href="{% url 'client:client-list' %}" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Back</a>
                        <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
                            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                                <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z">
                                </path>
                            </svg>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock content %}

client/templates/client/client_list.html
{% extends "client/base.html" %}

{% block title %}
clientList
{% endblock title %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">

        <h1 class="sm:text-3xl text-2xl font-medium title-font text-center text-gray-900 mb-20">List of the Client
            present in the Database

        </h1>
        <h3 class="font-medium title-font text-center text-indigo-500 mb-20">
            <p>
                <a  href="{% url 'client:client-category' %}">View the Categories

                </a>
            </p>
        </h3>

        <div class="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4 md:space-y-0 space-y-6">
            {% for client in clients %}
            <div class="p-4 md:w-1/3 flex">
                <div
                    class="w-12 h-12 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4 flex-shrink-0">
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                        stroke-width="2" class="w-6 h-6" viewBox="0 0 24 24">
                        <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                    </svg>
                </div>
                <div class="flex-grow pl-6">
                    <h2 class="text-gray-900 text-lg title-font font-medium mb-2">{{ client.first_name }} {{ client.last_name }} </h2>
                    <p class="leading-relaxed text-base">Age: {{ client.age }}, Source: {{ client.source }}</p>
                    <p class="leading-relaxed text-base">Current Status: {{ client.category }}</p>
                    <a href="{% url 'client:client-info' client.pk %}"
                        class="mt-3 text-indigo-500 inline-flex items-center">View this Client info
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                            <path d="M5 12h14M12 5l7 7-7 7"></path>
                        </svg>
                    </a>
                </div>
            </div>
            {% empty %}
            <p>There are currently no leads</p>
            {% endfor %}

        </div>
    </div>
    <div class="container px-5 py-24 mx-auto">
        <hr>
            <h1 class="sm:text-3xl text-2xl font-medium title-font text-center text-gray-900 mb-20">List of the Unassigned Clients present in the Database
            </h1>
        <div class="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4 md:space-y-0 space-y-6">

            {% if unassigned_clients.exists %}
            {% for unclient in unassigned_clients %}


                    <div class="w-12 h-12 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4 flex-shrink-0">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="w-6 h-6" viewBox="0 0 24 24">
                            <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                        </svg>
                    </div>
                    <div class="flex-grow pl-6">
                        <h2 class="text-gray-900 text-lg title-font font-medium mb-2">{{ unclient.first_name }} {{ unclient.last_name }} </h2>
                        <p class="leading-relaxed text-base">Age: {{ unclient.age }} {{ unclient.source }}</p>
                        <a href="{% url 'client:client-assign' unclient.pk %}"
                            class="mt-3 text-indigo-500 inline-flex items-center">Assign Chitfund
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>

                {% endfor %}
            {% endif %}
        </div>
    </div>
    {% if request.user.is_chitfund_owner %}
            <div class="sm:text-3xl text-2xl font-medium title-font text-center text-gray-900 mb-20">
            <a href="{% url 'client:client-create' %}"
                class="mt-3 text-red-500 inline-flex items-center hover:text-blue-500">Create New Client </a>
            </div>
    {% endif %}
</section>

{% endblock content %}

client/templates/client/client_restrict.html
{% extends "base.html" %}

{% block title %}
    ClientRestrict
{% endblock title %}

{% block content %}
    <div class="max-w-lg mx-auto">

        <div class="py-5 border-b border-gray-200">
            <a class="hover:text-blue-500" href="{% url 'home' %}">Go Back</a>
        </div>
        <h1 class="mt-5 text-4xl text-gray-800" > Hi {{ request.user.username }} You are not Authorised or Subscribed for Chitfund App!! </h1>
    </div>
{% endblock content %}

client/templates/client/client_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block title %}
clientUpdate
{% endblock title %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">Client</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">This are the details for {{ client.first_name }} {{ client.last_name }}</h1>
                <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
                src="https://dummyimage.com/400x400">
                <div class="flex mb-4">
                    <a href="{% url 'client:client-info' client.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
                    <a href="{% url 'client:client-category-update' client.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
                    <a href="{% url 'client:client-update' client.pk %}"
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update
                        Details</a>
                </div>
                <form method="POST" action="#">
                    {% csrf_token %} <!--Security aspect of Django -->
                    {{ form|crispy }}
                    <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md" >Submit</button>
                </form>
                <br>
                <div class="py-5 border-t border-gray-200 mt-5" >
                    <a href="{% url 'client:client-delete' client.pk %}"
                        class="w-full mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete
                    </a>
                </div>

            </div>

        </div>
    </div>
</section>

{% endblock content %}